In [1]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv("simple_life_expectancy.csv")

In [28]:
df

,Country; Year,Life expectancy at birth (years); Both sexes,Life expectancy at birth (years); Female,Life expectancy at birth (years); Male,Life expectancy at age 60 (years); Both sexes,Life expectancy at age 60 (years); Female,Life expectancy at age 60 (years); Male,Healthy life expectancy (HALE) at birth (years); Both sexes,Healthy life expectancy (HALE) at birth (years); Female,Healthy life expectancy (HALE) at birth (years); Male
0,Afghanistan; 2013,61,62,61,16,17,15,50,50,50
1,Afghanistan; 2012,60,61,58,16,17,15,49,49,49
2,Afghanistan; 2000,55,56,54,15,16,14,45,45,45
3,Afghanistan; 1990,49,50,49,14,15,13,NaN,NaN,NaN
4,Albania; 2013,74,76,73,19,20,18,65,66,64
5,Albania; 2012,74,75,73,19,20,18,65,66,64
6,Albania; 2000,70,73,68,17,18,15,62,64,60
7,Albania; 1990,69,71,67,16,18,15,NaN,NaN,NaN
8,Algeria; 2013,72,74,70,18,19,17,62,63,62
9,Algeria; 2012,72,73,70,18,19,17,62,63,62
10,Algeria; 2000,70,71,68,18,18,17,60,61,59
11,Algeria; 1990,68,69,66,17,18,16,NaN,NaN,NaN
12,Andorra; 2013,83,86,79,25,28,23,72,74,70
13,Andorra; 2012,83,86,79,25,28,23,72,74,69
14,Andorra; 2000,80,83,76,23,26,21,69,72,67
15,Andorra; 1990,77,81,74,22,24,19,NaN,NaN,NaN
16,Angola; 2013,52,53,50,16,16,15,44,46,43
17,Angola; 2012,51,52,50,16,16,15,44,45,43
18,Angola; 2000,46,47,44,15,15,14,39,40,38
19,Angola; 1990,43,45,41,14,14,13,NaN,NaN,NaN
20,Antigua and Barbuda; 2013,75,77,73,22,23,21,64,66,63
21,Antigua and Barbuda; 2012,75,77,73,22,23,21,64,66,63
22,Antigua and Barbuda; 2000,73,74,72,20,20,20,64,65,63
23,Antigua and Barbuda; 1990,71,72,70,17,18,17,NaN,NaN,NaN
24,Argentina; 2013,76,80,73,22,24,19,67,69,64
25,Argentina; 2012,76,79,73,21,24,19,67,69,64
26,Argentina; 2000,75,78,71,21,23,18,65,68,62
27,Argentina; 1990,73,76,69,20,22,17,NaN,NaN,NaN
28,Armenia; 2013,71,75,67,17,19,15,62,66,59
29,Armenia; 2012,71,75,67,17,19,15,62,66,59
...,...,...,...,...,...,...,...,...,...,...
746,Uruguay; 2000,75,79,71,21,23,18,66,68,63
747,Uruguay; 1990,73,76,69,19,21,17,NaN,NaN,NaN
748,Uzbekistan; 2013,69,72,67,17,18,16,61,62,59
749,Uzbekistan; 2012,69,72,67,17,18,16,60,62,59
750,Uzbekistan; 2000,66,69,63,17,18,15,58,60,56
751,Uzbekistan; 1990,67,70,63,18,20,16,NaN,NaN,NaN
752,Vanuatu; 2013,72,74,71,18,19,17,62,64,61
753,Vanuatu; 2012,72,74,70,18,19,17,62,63,61
754,Vanuatu; 2000,69,71,67,17,18,16,59,60,58
755,Vanuatu; 1990,66,67,64,16,17,15,NaN,NaN,NaN
756,Venezuela (Bolivarian Republic of); 2013,76,80,72,23,25,22,66,69,63
757,Venezuela (Bolivarian Republic of); 2012,76,80,72,23,24,21,66,69,63
758,Venezuela (Bolivarian Republic of); 2000,74,77,71,21,22,20,64,67,62
759,Venezuela (Bolivarian Republic of); 1990,72,74,70,19,20,18,NaN,NaN,NaN
760,Viet Nam; 2013,76,80,71,22,25,19,66,70,62
761,Viet Nam; 2012,76,80,71,22,25,19,66,69,62
762,Viet Nam; 2000,73,78,69,21,24,18,63,67,60
763,Viet Nam; 1990,70,75,66,20,23,18,NaN,NaN,NaN
764,Yemen; 2013,64,66,63,16,17,15,55,55,54
765,Yemen; 2012,64,65,62,16,17,15,54,55,54
766,Yemen; 2000,61,62,59,16,17,15,51,52,51
767,Yemen; 1990,58,59,56,16,16,15,NaN,NaN,NaN
768,Zambia; 2013,58,60,57,17,18,16,50,51,49
769,Zambia; 2012,57,58,55,17,18,16,49,50,48
770,Zambia; 2000,41,43,40,15,16,14,36,37,35
771,Zambia; 1990,43,47,40,15,16,14,NaN,NaN,NaN
772,Zimbabwe; 2013,59,61,56,18,19,17,50,52,48
773,Zimbabwe; 2012,58,60,56,18,19,17,49,51,47
774,Zimbabwe; 2000,42,42,42,16,16,15,37,36,37
775,Zimbabwe; 1990,62,64,60,18,18,17,NaN,NaN,NaN

In [29]:
df.columns

Index(['Country; Year', 'Life expectancy at birth (years); Both sexes',
       'Life expectancy at birth (years); Female',
       'Life expectancy at birth (years); Male',
       'Life expectancy at age 60 (years); Both sexes',
       'Life expectancy at age 60 (years); Female',
       'Life expectancy at age 60 (years); Male',
       'Healthy life expectancy (HALE) at birth (years); Both sexes',
       'Healthy life expectancy (HALE) at birth (years); Female',
       'Healthy life expectancy (HALE) at birth (years); Male'],
      dtype='object')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 10 columns):
Country; Year                                                  776 non-null object
Life expectancy at birth (years); Both sexes                   776 non-null int64
Life expectancy at birth (years); Female                       776 non-null int64
Life expectancy at birth (years); Male                         776 non-null int64
Life expectancy at age 60 (years); Both sexes                  776 non-null int64
Life expectancy at age 60 (years); Female                      776 non-null int64
Life expectancy at age 60 (years); Male                        776 non-null int64
Healthy life expectancy (HALE) at birth (years); Both sexes    582 non-null object
Healthy life expectancy (HALE) at birth (years); Female        582 non-null object
Healthy life expectancy (HALE) at birth (years); Male          582 non-null object
dtypes: int64(6), object(4)
memory usage: 60.7+ KB

In [26]:
df.ix[1:,3].max()

'87'

In [33]:
df2 = pd.read_csv("access_to_water.csv")

In [34]:
df2

,Country; Year,Population using improved drinking-water sources (%); Rural,Population using improved drinking-water sources (%); Urban,Population using improved drinking-water sources (%); Total,Population using improved sanitation facilities (%); Rural,Population using improved sanitation facilities (%); Urban,Population using improved sanitation facilities (%); Total
0,Afghanistan; 2015,47.0,78.2,55.3,27.0,45.1,31.9
1,Afghanistan; 2000,24.3,52.2,30.3,21.3,31.2,23.4
2,Albania; 2015,95.2,94.9,95.1,90.2,95.5,93.2
3,Albania; 2000,93.3,100.0,96.1,75.2,94.8,83.4
4,Albania; 1990,NaN,100.0,NaN,68.7,94.5,78.1
5,Algeria; 2015,81.8,84.3,83.6,82.2,89.8,87.6
6,Algeria; 2000,84.0,93.2,89.5,72.3,91.2,83.6
7,Algeria; 1990,85.0,97.4,91.5,67.7,91.8,80.3
8,Andorra; 2015,100.0,100.0,100.0,100.0,100.0,100.0
9,Andorra; 2000,100.0,100.0,100.0,100.0,100.0,100.0
10,Andorra; 1990,100.0,100.0,100.0,100.0,100.0,100.0
11,Angola; 2015,28.2,75.4,49.0,22.5,88.6,51.6
12,Angola; 2000,38.7,60.3,45.7,12.5,73.0,32.1
13,Angola; 1990,43.5,52.1,45.7,7.9,64.6,22.4
14,Antigua and Barbuda; 2015,97.9,97.9,97.9,NaN,NaN,NaN
15,Antigua and Barbuda; 2000,97.7,97.7,97.7,84.6,84.6,84.6
16,Antigua and Barbuda; 1990,97.4,97.4,97.4,74.7,74.7,74.7
17,Argentina; 2015,100.0,99.0,99.1,98.3,96.2,96.4
18,Argentina; 2000,81.3,98.1,96.3,81.9,92.5,91.4
19,Argentina; 1990,68.8,97.5,93.8,69.9,90.1,87.4
20,Armenia; 2015,100.0,100.0,100.0,78.2,96.2,89.5
21,Armenia; 2000,81.7,98.5,92.6,78.3,95.4,89.3
22,Armenia; 1990,NaN,98.1,NaN,NaN,95.1,NaN
23,Australia; 2015,100.0,100.0,100.0,100.0,100.0,100.0
24,Australia; 2000,100.0,100.0,100.0,100.0,100.0,100.0
25,Australia; 1990,100.0,100.0,100.0,100.0,100.0,100.0
26,Austria; 2015,100.0,100.0,100.0,100.0,100.0,100.0
27,Austria; 2000,100.0,100.0,100.0,100.0,100.0,100.0
28,Austria; 1990,100.0,100.0,100.0,100.0,100.0,100.0
29,Azerbaijan; 2015,77.8,94.7,87.0,86.6,91.6,89.3
...,...,...,...,...,...,...,...
528,United Kingdom of Great Britain and Northern I...,100.0,100.0,100.0,99.6,99.1,99.2
529,United Republic of Tanzania; 2015,45.5,77.2,55.6,8.3,31.3,15.6
530,United Republic of Tanzania; 2000,45.3,85.9,54.4,7.2,16.3,9.3
531,United Republic of Tanzania; 1990,45.2,91.6,53.9,6.6,6.3,6.5
532,United States of America; 2015,98.2,99.4,99.2,100.0,100.0,100.0
533,United States of America; 2000,95.8,99.6,98.8,99.2,99.9,99.7
534,United States of America; 1990,94.0,99.8,98.4,98.6,99.8,99.5
535,Uruguay; 2015,93.9,100.0,99.7,92.6,96.6,96.4
536,Uruguay; 2000,77.0,98.5,96.8,84.3,94.3,93.5
537,Uruguay; 1990,70.3,97.8,94.8,81.0,93.3,92.0
538,Uzbekistan; 2015,NaN,98.5,NaN,100.0,100.0,100.0
539,Uzbekistan; 2000,83.4,97.6,88.7,86.9,97.5,90.9
540,Uzbekistan; 1990,85.3,97.0,90.0,75.8,95.4,83.7
541,Vanuatu; 2015,92.9,98.9,94.5,55.4,65.1,57.9
542,Vanuatu; 2000,70.3,95.7,75.8,38.1,54.4,41.7
543,Vanuatu; 1990,55.2,93.5,62.4,NaN,NaN,NaN
544,Venezuela (Bolivarian Republic of); 2015,77.9,95.0,93.1,69.9,97.5,94.4
545,Venezuela (Bolivarian Republic of); 2000,72.5,93.6,91.1,56.0,92.7,88.3
546,Venezuela (Bolivarian Republic of); 1990,68.4,92.6,88.8,45.3,89.0,82.1
547,Viet Nam; 2015,96.9,99.1,97.6,69.7,94.4,78.0
548,Viet Nam; 2000,72.2,93.6,77.4,45.2,76.7,52.9
549,Viet Nam; 1990,55.7,90.0,62.7,28.9,64.9,36.2
550,Yemen; 2000,51.9,82.5,59.9,24.1,82.4,39.4
551,Yemen; 1990,58.5,95.7,66.3,11.5,69.8,23.7
552,Zambia; 2015,51.3,85.6,65.4,35.7,55.6,43.9
553,Zambia; 2000,34.7,87.3,53.0,31.5,57.6,40.6
554,Zambia; 1990,23.6,88.4,49.2,28.6,58.9,40.6
555,Zimbabwe; 2015,67.3,97.0,76.9,30.8,49.3,36.8
556,Zimbabwe; 2000,69.6,98.6,79.4,33.3,50.8,39.2
557,Zimbabwe; 1990,71.2,99.6,79.4,35.0,51.9,39.9

In [36]:
df2['Country'], df2['Year'] = zip(*df2['Country; Year'].apply(lambda x: x.split('; ', 1)))

In [43]:
len(df2['Country'].unique())

192

In [44]:
df2

,Country; Year,Population using improved drinking-water sources (%); Rural,Population using improved drinking-water sources (%); Urban,Population using improved drinking-water sources (%); Total,Population using improved sanitation facilities (%); Rural,Population using improved sanitation facilities (%); Urban,Population using improved sanitation facilities (%); Total,Country,Year
0,Afghanistan; 2015,47.0,78.2,55.3,27.0,45.1,31.9,Afghanistan,2015
1,Afghanistan; 2000,24.3,52.2,30.3,21.3,31.2,23.4,Afghanistan,2000
2,Albania; 2015,95.2,94.9,95.1,90.2,95.5,93.2,Albania,2015
3,Albania; 2000,93.3,100.0,96.1,75.2,94.8,83.4,Albania,2000
4,Albania; 1990,NaN,100.0,NaN,68.7,94.5,78.1,Albania,1990
5,Algeria; 2015,81.8,84.3,83.6,82.2,89.8,87.6,Algeria,2015
6,Algeria; 2000,84.0,93.2,89.5,72.3,91.2,83.6,Algeria,2000
7,Algeria; 1990,85.0,97.4,91.5,67.7,91.8,80.3,Algeria,1990
8,Andorra; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Andorra,2015
9,Andorra; 2000,100.0,100.0,100.0,100.0,100.0,100.0,Andorra,2000
10,Andorra; 1990,100.0,100.0,100.0,100.0,100.0,100.0,Andorra,1990
11,Angola; 2015,28.2,75.4,49.0,22.5,88.6,51.6,Angola,2015
12,Angola; 2000,38.7,60.3,45.7,12.5,73.0,32.1,Angola,2000
13,Angola; 1990,43.5,52.1,45.7,7.9,64.6,22.4,Angola,1990
14,Antigua and Barbuda; 2015,97.9,97.9,97.9,NaN,NaN,NaN,Antigua and Barbuda,2015
15,Antigua and Barbuda; 2000,97.7,97.7,97.7,84.6,84.6,84.6,Antigua and Barbuda,2000
16,Antigua and Barbuda; 1990,97.4,97.4,97.4,74.7,74.7,74.7,Antigua and Barbuda,1990
17,Argentina; 2015,100.0,99.0,99.1,98.3,96.2,96.4,Argentina,2015
18,Argentina; 2000,81.3,98.1,96.3,81.9,92.5,91.4,Argentina,2000
19,Argentina; 1990,68.8,97.5,93.8,69.9,90.1,87.4,Argentina,1990
20,Armenia; 2015,100.0,100.0,100.0,78.2,96.2,89.5,Armenia,2015
21,Armenia; 2000,81.7,98.5,92.6,78.3,95.4,89.3,Armenia,2000
22,Armenia; 1990,NaN,98.1,NaN,NaN,95.1,NaN,Armenia,1990
23,Australia; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Australia,2015
24,Australia; 2000,100.0,100.0,100.0,100.0,100.0,100.0,Australia,2000
25,Australia; 1990,100.0,100.0,100.0,100.0,100.0,100.0,Australia,1990
26,Austria; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Austria,2015
27,Austria; 2000,100.0,100.0,100.0,100.0,100.0,100.0,Austria,2000
28,Austria; 1990,100.0,100.0,100.0,100.0,100.0,100.0,Austria,1990
29,Azerbaijan; 2015,77.8,94.7,87.0,86.6,91.6,89.3,Azerbaijan,2015
...,...,...,...,...,...,...,...,...,...
528,United Kingdom of Great Britain and Northern I...,100.0,100.0,100.0,99.6,99.1,99.2,United Kingdom of Great Britain and Northern I...,1990
529,United Republic of Tanzania; 2015,45.5,77.2,55.6,8.3,31.3,15.6,United Republic of Tanzania,2015
530,United Republic of Tanzania; 2000,45.3,85.9,54.4,7.2,16.3,9.3,United Republic of Tanzania,2000
531,United Republic of Tanzania; 1990,45.2,91.6,53.9,6.6,6.3,6.5,United Republic of Tanzania,1990
532,United States of America; 2015,98.2,99.4,99.2,100.0,100.0,100.0,United States of America,2015
533,United States of America; 2000,95.8,99.6,98.8,99.2,99.9,99.7,United States of America,2000
534,United States of America; 1990,94.0,99.8,98.4,98.6,99.8,99.5,United States of America,1990
535,Uruguay; 2015,93.9,100.0,99.7,92.6,96.6,96.4,Uruguay,2015
536,Uruguay; 2000,77.0,98.5,96.8,84.3,94.3,93.5,Uruguay,2000
537,Uruguay; 1990,70.3,97.8,94.8,81.0,93.3,92.0,Uruguay,1990
538,Uzbekistan; 2015,NaN,98.5,NaN,100.0,100.0,100.0,Uzbekistan,2015
539,Uzbekistan; 2000,83.4,97.6,88.7,86.9,97.5,90.9,Uzbekistan,2000
540,Uzbekistan; 1990,85.3,97.0,90.0,75.8,95.4,83.7,Uzbekistan,1990
541,Vanuatu; 2015,92.9,98.9,94.5,55.4,65.1,57.9,Vanuatu,2015
542,Vanuatu; 2000,70.3,95.7,75.8,38.1,54.4,41.7,Vanuatu,2000
543,Vanuatu; 1990,55.2,93.5,62.4,NaN,NaN,NaN,Vanuatu,1990
544,Venezuela (Bolivarian Republic of); 2015,77.9,95.0,93.1,69.9,97.5,94.4,Venezuela (Bolivarian Republic of),2015
545,Venezuela (Bolivarian Republic of); 2000,72.5,93.6,91.1,56.0,92.7,88.3,Venezuela (Bolivarian Republic of),2000
546,Venezuela (Bolivarian Republic of); 1990,68.4,92.6,88.8,45.3,89.0,82.1,Venezuela (Bolivarian Republic of),1990
547,Viet Nam; 2015,96.9,99.1,97.6,69.7,94.4,78.0,Viet Nam,2015
548,Viet Nam; 2000,72.2,93.6,77.4,45.2,76.7,52.9,Viet Nam,2000
549,Viet Nam; 1990,55.7,90.0,62.7,28.9,64.9,36.2,Viet Nam,1990
550,Yemen; 2000,51.9,82.5,59.9,24.1,82.4,39.4,Yemen,2000
551,Yemen; 1990,58.5,95.7,66.3,11.5,69.8,23.7,Yemen,1990
552,Zambia; 2015,51.3,85.6,65.4,35.7,55.6,43.9,Zambia,2015
553,Zambia; 2000,34.7,87.3,53.0,31.5,57.6,40.6,Zambia,2000
554,Zambia; 1990,23.6,88.4,49.2,28.6,58.9,40.6,Zambia,1990
555,Zimbabwe; 2015,67.3,97.0,76.9,30.8,49.3,36.8,Zimbabwe,2015
556,Zimbabwe; 2000,69.6,98.6,79.4,33.3,50.8,39.2,Zimbabwe,2000
557,Zimbabwe; 1990,71.2,99.6,79.4,35.0,51.9,39.9,Zimbabwe,1990

In [52]:
df2[df2.Year == '2015'][]

,Country; Year,Population using improved drinking-water sources (%); Rural,Population using improved drinking-water sources (%); Urban,Population using improved drinking-water sources (%); Total,Population using improved sanitation facilities (%); Rural,Population using improved sanitation facilities (%); Urban,Population using improved sanitation facilities (%); Total,Country,Year
0,Afghanistan; 2015,47.0,78.2,55.3,27.0,45.1,31.9,Afghanistan,2015
2,Albania; 2015,95.2,94.9,95.1,90.2,95.5,93.2,Albania,2015
5,Algeria; 2015,81.8,84.3,83.6,82.2,89.8,87.6,Algeria,2015
8,Andorra; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Andorra,2015
11,Angola; 2015,28.2,75.4,49.0,22.5,88.6,51.6,Angola,2015
14,Antigua and Barbuda; 2015,97.9,97.9,97.9,NaN,NaN,NaN,Antigua and Barbuda,2015
17,Argentina; 2015,100.0,99.0,99.1,98.3,96.2,96.4,Argentina,2015
20,Armenia; 2015,100.0,100.0,100.0,78.2,96.2,89.5,Armenia,2015
23,Australia; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Australia,2015
26,Austria; 2015,100.0,100.0,100.0,100.0,100.0,100.0,Austria,2015
29,Azerbaijan; 2015,77.8,94.7,87.0,86.6,91.6,89.3,Azerbaijan,2015
32,Bahamas; 2015,98.4,98.4,98.4,92.0,92.0,92.0,Bahamas,2015
34,Bahrain; 2015,100.0,100.0,100.0,99.2,99.2,99.2,Bahrain,2015
37,Bangladesh; 2015,87.0,86.5,86.9,62.1,57.7,60.6,Bangladesh,2015
40,Barbados; 2015,99.7,99.7,99.7,96.2,96.2,96.2,Barbados,2015
43,Belarus; 2015,99.1,99.9,99.7,95.2,94.1,94.3,Belarus,2015
46,Belgium; 2015,100.0,100.0,100.0,99.4,99.5,99.5,Belgium,2015
49,Belize; 2015,100.0,98.9,99.5,88.2,93.5,90.5,Belize,2015
52,Benin; 2015,72.1,85.2,77.9,7.3,35.6,19.7,Benin,2015
55,Bhutan; 2015,100.0,100.0,100.0,33.1,77.9,50.4,Bhutan,2015
58,Bolivia (Plurinational State of); 2015,75.6,96.7,90.0,27.5,60.8,50.3,Bolivia (Plurinational State of),2015
61,Bosnia and Herzegovina; 2015,100.0,99.7,99.9,92.0,98.9,94.8,Bosnia and Herzegovina,2015
64,Botswana; 2015,92.3,99.2,96.2,43.1,78.5,63.4,Botswana,2015
67,Brazil; 2015,87.0,100.0,98.1,51.5,88.0,82.8,Brazil,2015
70,Bulgaria; 2015,99.0,99.6,99.4,83.7,86.8,86.0,Bulgaria,2015
73,Burkina Faso; 2015,75.8,97.5,82.3,6.7,50.4,19.7,Burkina Faso,2015
76,Burundi; 2015,73.8,91.1,75.9,48.6,43.8,48.0,Burundi,2015
79,Cote d'Ivoire; 2015,68.8,93.1,81.9,10.3,32.8,22.5,Cote d'Ivoire,2015
82,Cabo Verde; 2015,87.3,94.0,91.7,54.3,81.6,72.2,Cabo Verde,2015
84,Cambodia; 2015,69.1,100.0,75.5,30.5,88.1,42.4,Cambodia,2015
...,...,...,...,...,...,...,...,...,...
464,Spain; 2015,100.0,100.0,100.0,100.0,99.8,99.9,Spain,2015
467,Sri Lanka; 2015,95.0,98.5,95.6,96.7,88.1,95.1,Sri Lanka,2015
472,Suriname; 2015,88.4,98.1,94.8,61.4,88.4,79.2,Suriname,2015
475,Swaziland; 2015,68.9,93.6,74.1,56.0,63.1,57.5,Swaziland,2015
478,Sweden; 2015,100.0,100.0,100.0,99.6,99.3,99.3,Sweden,2015
481,Switzerland; 2015,100.0,100.0,100.0,99.8,99.9,99.9,Switzerland,2015
484,Syrian Arab Republic; 2015,87.2,92.3,90.1,95.1,96.2,95.7,Syrian Arab Republic,2015
487,Tajikistan; 2015,66.7,93.1,73.8,95.5,93.8,95.0,Tajikistan,2015
490,Thailand; 2015,98.0,97.6,97.8,96.1,89.9,93.0,Thailand,2015
493,The former Yugoslav republic of Macedonia; 2015,98.9,99.8,99.4,82.6,97.2,90.9,The former Yugoslav republic of Macedonia,2015
496,Timor-Leste; 2015,60.5,95.2,71.9,26.8,69.0,40.6,Timor-Leste,2015
498,Togo; 2015,44.2,91.4,63.1,2.9,24.7,11.6,Togo,2015
501,Tonga; 2015,99.6,99.7,99.6,89.0,97.6,91.0,Tonga,2015
504,Trinidad and Tobago; 2015,95.1,95.1,95.1,91.5,91.5,91.5,Trinidad and Tobago,2015
507,Tunisia; 2015,93.2,100.0,97.7,79.8,97.4,91.6,Tunisia,2015
510,Turkey; 2015,100.0,100.0,100.0,85.5,98.3,94.9,Turkey,2015
514,Tuvalu; 2015,97.0,98.3,97.7,NaN,86.3,NaN,Tuvalu,2015
517,Uganda; 2015,75.8,95.5,79.0,17.3,28.5,19.1,Uganda,2015
520,Ukraine; 2015,97.8,95.5,96.2,92.6,97.4,95.9,Ukraine,2015
523,United Arab Emirates; 2015,100.0,99.6,99.6,95.2,98.0,97.6,United Arab Emirates,2015
526,United Kingdom of Great Britain and Northern I...,100.0,100.0,100.0,99.6,99.1,99.2,United Kingdom of Great Britain and Northern I...,2015
529,United Republic of Tanzania; 2015,45.5,77.2,55.6,8.3,31.3,15.6,United Republic of Tanzania,2015
532,United States of America; 2015,98.2,99.4,99.2,100.0,100.0,100.0,United States of America,2015
535,Uruguay; 2015,93.9,100.0,99.7,92.6,96.6,96.4,Uruguay,2015
538,Uzbekistan; 2015,NaN,98.5,NaN,100.0,100.0,100.0,Uzbekistan,2015
541,Vanuatu; 2015,92.9,98.9,94.5,55.4,65.1,57.9,Vanuatu,2015
544,Venezuela (Bolivarian Republic of); 2015,77.9,95.0,93.1,69.9,97.5,94.4,Venezuela (Bolivarian Republic of),2015
547,Viet Nam; 2015,96.9,99.1,97.6,69.7,94.4,78.0,Viet Nam,2015
552,Zambia; 2015,51.3,85.6,65.4,35.7,55.6,43.9,Zambia,2015
555,Zimbabwe; 2015,67.3,97.0,76.9,30.8,49.3,36.8,Zimbabwe,2015